services:
  - type: web
    name: career-match
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false